header_include_path: object_detector/object_detector.hpp
namespace: object_detector
node_class_name: ObjectDetector

params:
  always_publish_stream:
    type: bool
    default_value: false
    description: "Whether to always publish video feed even without detections."
    constraints: ""
    read_only: false
    var_name: always_publish_stream_

  autostart:
    type: bool
    default_value: false
    description: "Whether to start detection immediately."
    constraints: "Cannot be changed."
    read_only: true
    var_name: autostart_

  classes:
    type: string_array
    default_value:
      - ''
    description: "Names of classes that the model will detect."
    constraints: "Only used when use_coco_dataset is false, cannot be changed."
    read_only: true
    var_name: classes_

  classes_targets:
    type: string_array
    default_value:
      - ''
    description: "Class names of the targets to detect."
    constraints: "Cannot be changed."
    read_only: true
    var_name: classes_targets_

  detection_depth_topics:
    type: string_array
    default_value:
      - ''
    description: "Names of the input topics to subscribe to for depth map data."
    constraints: "Must match corresponding input topics and other parameters, fill with empty strings if necessary."
    read_only: true

  detection_distances_topics:
    type: string_array
    default_value:
      - ''
    description: "Names of the input topics to subscribe to for distance data."
    constraints: "Must match corresponding input topics and other parameters, fill with empty strings if necessary."
    read_only: true

  detection_output_topics:
    type: string_array
    default_value:
      - '/detections'
    description: "Names of the output topics to publish detection results."
    constraints: "Must match corresponding input topics."
    read_only: true

  detection_visual_output_topics:
    type: string_array
    default_value:
      - '/detections_visual'
    description: "Names of the output topics to publish visual detection results."
    constraints: "Must match corresponding input topics."
    read_only: true

  detection_stream_topics:
    type: string_array
    default_value:
      - '/detections_stream'
    description: "Names of the output topics to publish detection video feed."
    constraints: "Must match corresponding input topics."
    read_only: true

  model_NMS_threshold:
    type: double
    default_value: 0.1
    min_value: 0.0
    max_value: 1.0
    step: 0.0
    description: "YOLO NMS threshold."
    constraints: "Can be changed."
    read_only: false
    var_name: model_NMS_threshold_

  model_path:
    type: string
    default_value: ''
    description: "Path to neural network model file."
    constraints: "Must be a valid path to a model file in ONNX format."
    read_only: true
    var_name: model_path_

  model_score_threshold:
    type: double
    default_value: 0.1
    min_value: 0.0
    max_value: 1.0
    step: 0.0
    description: "YOLO score threshold."
    constraints: "Can be changed."
    read_only: false
    var_name: model_score_threshold_

  model_shape:
    type: integer_array
    default_value: [0]
    min_value: 1
    max_value: 10000
    step: 1
    description: "Model input dimensions."
    constraints: "Cannot be changed."
    read_only: true
    var_name: model_shape_

  subscriber_base_topic_name:
    type: string_array
    default_value:
      - ''
    description: "Base name of the input topics to be passed to image_transport APIs."
    constraints: "Cannot be changed, must be an array of valid ROS 2 topic family names for image_transport."
    read_only: true

  subscriber_best_effort_qos:
    type: bool_array
    default_value:
      - false
    description: "Whether to subscribe to input topics with a best effort QoS."
    constraints: "Cannot be changed."
    read_only: true

  subscriber_depth:
    type: integer_array
    default_value:
      - 1
    min_value: 0
    max_value: 100
    step: 1
    description: "image_transport subscribers queue depths."
    constraints: "Cannot be changed."
    read_only: true

  subscriber_transport:
    type: string_array
    default_value:
      - raw
    description: "Transport types to use with image_transport."
    constraints: "Cannot be changed."
    read_only: true

  use_coco_classes:
    type: bool
    default_value: false
    description: "Whether to use COCO classes."
    constraints: "Cannot be changed."
    read_only: true
    var_name: use_coco_classes_

  use_depth:
    type: bool_array
    default_value:
      - false
    description: "Whether to use depth map data to estimate object position."
    constraints: "Must match corresponding input topics, checked before use_distances."
    read_only: true

  use_distances:
    type: bool_array
    default_value:
      - false
    description: "Whether to use distance data to estimate object position."
    constraints: "Must match corresponding input topics, checked after use_depth."
    read_only: true

  use_gpu:
    type: bool
    default_value: false
    description: "Whether to use GPU acceleration to run YOLO."
    constraints: "Cannot be changed."
    read_only: true
    var_name: use_gpu_

  verbose:
    type: bool
    default_value: false
    description: "Enables debug log messages."
    constraints: ""
    read_only: false
    var_name: verbose_

  worker_cpu:
    type: integer
    default_value: -1
    min_value: -1
    max_value: 255
    step: 1
    description: "CPU on which the worker thread will be pinned."
    constraints: "Cannot be changed, -1 disables this policy, useful when not using GPU."
    read_only: true
    var_name: worker_cpu_
