/object_detector:
  ros__parameters:
    always_publish_stream: true
    autostart: true
    classes:
      - drone
    classes_targets:
      - 'potted plant'
      - 'teddy bear'
      - 'traffic light'
      - 'fire hydrant'
    model_NMS_threshold: 0.5
    model_path: /home/neo/workspace/logs/yolov8n-seg.onnx
    model_score_threshold: 0.5
    model_shape: [640, 480]
    detection_depth_topics:
      - ''
      - ''
      - ''
    detection_distances_topics:
      - ''
      - ''
      - ''
    detection_output_topics:
      - '/found_targets'
      - ''
      - ''
    detection_visual_output_topics:
      - '/found_targets/visual'
      - ''
      - ''
    detection_stream_topics:
      - '/detector/front'
      - ''
      - ''
    subscriber_base_topic_name:
      - '/camera/image_rect_color'
      - ''
      - ''
    subscriber_best_effort_qos:
      - true
      - true
      - true
    subscriber_depth:
      - 2
      - 2
      - 2
    subscriber_transport:
      - compressed
      - ''
      - ''
    use_coco_classes: true
    use_depth:
      - false
      - false
      - false
    use_distances:
      - true
      - false
      - false
    use_gpu: true
    verbose: true
    worker_cpu: -1
