/object_detector:
  ros__parameters:
    always_publish_stream: true
    autostart: true
    classes:
      - drone
    classes_targets:
      - person
      - bottle
    distance_centroid_radius: 10
    model_NMS_threshold: 0.5
    model_path: /home/neo/workspace/logs/yolov8n-seg.onnx
    model_score_threshold: 0.5
    model_shape: [640, 480]
    subscriber_base_topic_name: /zed/zed_driver/left/sd/image_rect_color
    subscriber_best_effort_qos: false
    subscriber_depth: 5
    subscriber_transport: raw
    use_coco_classes: true
    use_distances: false
    use_depth: false
    use_gpu: true
    verbose: true
    worker_cpu: -1
