header_include_path: object_detector/object_detector.hpp
namespace: ObjectDetector
node_class_name: ObjectDetectorNode

params:
  always_pub_stream:
    type: bool
    default_value: false
    description: "Whether to always publish images even without detections."
    constraints: "Can be changed."
    read_only: false
    var_name: always_pub_stream_

  autostart:
    type: bool
    default_value: false
    description: "Whether to start detection immediately."
    constraints: "Cannot be changed."
    read_only: true
    var_name: autostart_

  best_effort_sub_qos:
    type: bool
    default_value: false
    description: "Whether to subscribe to the input topics with a best effort QoS."
    constraints: "Cannot be changed."
    read_only: true
    var_name: best_effort_sub_qos_

  classes:
    type: string_array
    default_value: [""]
    description: "Classes names."
    constraints: "Only used when use_coco_dataset is false. Cannot be changed."
    read_only: true
    var_name: classes_

  classes_targets:
    type: string_array
    default_value: [""]
    description: "Target classes names."
    constraints: "Cannot be changed."
    read_only: true
    var_name: classes_targets_

  model_shape:
    type: integer_array
    default_value: [0]
    min_value: 0
    max_value: 10000
    step: 1
    description: "Model input dimensions."
    constraints: "Cannot be changed."
    read_only: true
    var_name: model_shape_

  image_sub_depth:
    type: integer
    default_value: 1
    min_value: 0
    max_value: 100
    step: 1
    description: "Image subscriber queue depth."
    constraints: "Cannot be changed."
    read_only: true
    var_name: image_sub_depth_

  model_NMS_threshold:
    type: double
    default_value: 0.1
    min_value: 0.0
    max_value: 1.0
    step: 0.0
    description: "YOLO NMS threshold."
    constraints: "Can be changed."
    read_only: false
    var_name: model_NMS_threshold_

  model_score_threshold:
    type: double
    default_value: 0.1
    min_value: 0.0
    max_value: 1.0
    step: 0.0
    description: "YOLO score threshold."
    constraints: "Can be changed."
    read_only: false
    var_name: model_score_threshold_

  onnx_path:
    type: string
    default_value: /
    description: "Path to ONNX neural network."
    constraints: "Cannot be changed."
    read_only: true
    var_name: onnx_path_

  transport:
    type: string
    default_value: raw
    description: "Transport type to use with image_transport."
    constraints: "Cannot be changed."
    read_only: true
    var_name: transport_

  use_coco_classes:
    type: bool
    default_value: false
    description: "Whether to use COCO classes."
    constraints: "Cannot be changed."
    read_only: true
    var_name: use_coco_classes_

  use_gpu:
    type: bool
    default_value: false
    description: "Whether to use GPU to run YOLO."
    constraints: "Cannot be changed."
    read_only: true
    var_name: use_gpu_

  worker_cpu:
    type: integer
    default_value: -1
    min_value: -1
    max_value: 255
    step: 1
    description: "CPU on which the worker will be pinned."
    constraints: "Cannot be changed, -1 disables this policy."
    read_only: true
    var_name: worker_cpu_
